package com.yourname.demo.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.yourname.demo.model.Account;
 
/**
 * DAO interface for table: Account.
 * @author autogenerated
 */
public interface AccountDao extends GenericDAO<Account,  Long>  {
	// constructor only
}

