package com.yourname.demo.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.yourname.demo.model.Address;
 
/**
 * DAO interface for table: Address.
 * @author autogenerated
 */
public interface AddressDao extends GenericDAO<Address,  Long>  {
	// constructor only
}

