package com.yourname.demo.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.yourname.demo.model.CustomerTransaction;
 
/**
 * DAO interface for table: CustomerTransaction.
 * @author autogenerated
 */
public interface CustomerTransactionDao extends GenericDAO<CustomerTransaction,  Long>  {
	// constructor only
}

