package com.yourname.demo.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.yourname.demo.model.Customer;
 
/**
 * DAO interface for table: Customer.
 * @author autogenerated
 */
public interface CustomerDao extends GenericDAO<Customer,  Long>  {
	// constructor only
}

