package com.yourname.demo.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.yourname.demo.model.Address;
import org.springframework.stereotype.Repository;
import com.yourname.demo.model.dao.AddressDao;
 
 
/**
 * DAO for table: Address.
 * @author autogenerated
 */
@Repository
public class AddressDaoImpl extends GenericHibernateDaoImpl<Address, Long> implements AddressDao {
	
	/** Constructor method. */
		public AddressDaoImpl() {
			super(Address.class);
		}
	}

