package com.yourname.demo.model.factories;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import com.yourname.demo.model.dao.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateDemoDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateDemoDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateDemoDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateDemoDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a AccountDao instance.
	 * 
	 * @return a AccountDao instance
	 */
	public static AccountDao getAccountDao() {
		return (AccountDao) getBean("accountDaoImpl"); 
	}
	/**
	 * Returns a AddressDao instance.
	 * 
	 * @return a AddressDao instance
	 */
	public static AddressDao getAddressDao() {
		return (AddressDao) getBean("addressDaoImpl"); 
	}
	/**
	 * Returns a CustomerDao instance.
	 * 
	 * @return a CustomerDao instance
	 */
	public static CustomerDao getCustomerDao() {
		return (CustomerDao) getBean("customerDaoImpl"); 
	}
	/**
	 * Returns a CustomerTransactionDao instance.
	 * 
	 * @return a CustomerTransactionDao instance
	 */
	public static CustomerTransactionDao getCustomerTransactionDao() {
		return (CustomerTransactionDao) getBean("customerTransactionDaoImpl"); 
	}

}
