package com.yourname.demo.model.iface;
import com.yourname.demo.model.Customer;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: address.
 * @author autogenerated
 */

public interface IAddress {



    /**
     * Return the value associated with the column: city.
	 * @return A String object (this.city)
	 */
	String getCity();
	

  
    /**  
     * Set the value related to the column: city.
	 * @param city the city value you wish to set
	 */
	void setCity(final String city);

    /**
     * Return the value associated with the column: country.
	 * @return A String object (this.country)
	 */
	String getCountry();
	

  
    /**  
     * Set the value related to the column: country.
	 * @param country the country value you wish to set
	 */
	void setCountry(final String country);

    /**
     * Return the value associated with the column: customer.
	 * @return A Set&lt;Customer&gt; object (this.customer)
	 */
	Set<Customer> getCustomers();
	
	/**
	 * Adds a bi-directional link of type Customer to the customers set.
	 * @param customer item to add
	 */
	void addCustomer(Customer customer);

  
    /**  
     * Set the value related to the column: customer.
	 * @param customer the customer value you wish to set
	 */
	void setCustomers(final Set<Customer> customer);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: line1.
	 * @return A String object (this.line1)
	 */
	String getLine1();
	

  
    /**  
     * Set the value related to the column: line1.
	 * @param line1 the line1 value you wish to set
	 */
	void setLine1(final String line1);

    /**
     * Return the value associated with the column: line2.
	 * @return A String object (this.line2)
	 */
	String getLine2();
	

  
    /**  
     * Set the value related to the column: line2.
	 * @param line2 the line2 value you wish to set
	 */
	void setLine2(final String line2);

	// end of interface
}