package com.yourname.demo.model.iface;
import com.yourname.demo.model.Account;
import com.yourname.demo.model.Address;
import com.yourname.demo.model.CustomerTransaction;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: customer.
 * @author autogenerated
 */

public interface ICustomer {



    /**
     * Return the value associated with the column: account.
	 * @return A Set&lt;Account&gt; object (this.account)
	 */
	Set<Account> getAccounts();
	
	/**
	 * Adds a bi-directional link of type Account to the accounts set.
	 * @param account item to add
	 */
	void addAccount(Account account);

  
    /**  
     * Set the value related to the column: account.
	 * @param account the account value you wish to set
	 */
	void setAccounts(final Set<Account> account);

    /**
     * Return the value associated with the column: address1.
	 * @return A Address object (this.address1)
	 */
	Address getAddress1();
	

  
    /**  
     * Set the value related to the column: address1.
	 * @param address1 the address1 value you wish to set
	 */
	void setAddress1(final Address address1);

    /**
     * Return the value associated with the column: address2.
	 * @return A Address object (this.address2)
	 */
	Address getAddress2();
	

  
    /**  
     * Set the value related to the column: address2.
	 * @param address2 the address2 value you wish to set
	 */
	void setAddress2(final Address address2);

    /**
     * Return the value associated with the column: currentAccountOpeningBalance.
	 * @return A java.math.BigDecimal object (this.currentAccountOpeningBalance)
	 */
	java.math.BigDecimal getCurrentAccountOpeningBalance();
	

  
    /**  
     * Set the value related to the column: currentAccountOpeningBalance.
	 * @param currentAccountOpeningBalance the currentAccountOpeningBalance value you wish to set
	 */
	void setCurrentAccountOpeningBalance(final java.math.BigDecimal currentAccountOpeningBalance);

    /**
     * Return the value associated with the column: customerTransaction.
	 * @return A Set&lt;CustomerTransaction&gt; object (this.customerTransaction)
	 */
	Set<CustomerTransaction> getCustomerTransactions();
	
	/**
	 * Adds a bi-directional link of type CustomerTransaction to the customerTransactions set.
	 * @param customerTransaction item to add
	 */
	void addCustomerTransaction(CustomerTransaction customerTransaction);

  
    /**  
     * Set the value related to the column: customerTransaction.
	 * @param customerTransaction the customerTransaction value you wish to set
	 */
	void setCustomerTransactions(final Set<CustomerTransaction> customerTransaction);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: savingsAccountOpeningBalance.
	 * @return A java.math.BigDecimal object (this.savingsAccountOpeningBalance)
	 */
	java.math.BigDecimal getSavingsAccountOpeningBalance();
	

  
    /**  
     * Set the value related to the column: savingsAccountOpeningBalance.
	 * @param savingsAccountOpeningBalance the savingsAccountOpeningBalance value you wish to set
	 */
	void setSavingsAccountOpeningBalance(final java.math.BigDecimal savingsAccountOpeningBalance);

    /**
     * Return the value associated with the column: surname.
	 * @return A String object (this.surname)
	 */
	String getSurname();
	

  
    /**  
     * Set the value related to the column: surname.
	 * @param surname the surname value you wish to set
	 */
	void setSurname(final String surname);

	// end of interface
}